# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: cat /etc/debian_version; env
  displayName: Get hostname and env vars.
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: |
    pip install -r $(Build.SourcesDirectory)/create_environment/requirements.txt
  displayName: 'Install requirements'


