trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.9
    addToPath: true
    architecture: x64

- script: |
    cat /etc/debian_version
    pip install -r $(Build.SourcesDirectory)/create_environment/requirements.txt
  displayName: Install requirements


