trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.9
      addToPath: true
      architecture: x64

  - script: |
      cat /etc/debian_version
      pip install -r $(Build.SourcesDirectory)/create_environment/requirements.txt
    displayName: Install requirements
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(Build.SourcesDirectory)/create_environment/create_env.py'

