---
# tasks file for vim_config
# install prerequisite packages.

#- apt:
#    name: neovim
#    state: present
#  become: true

# Installing SpaceVim 
- get_url: 
    url: https://spacevim.org/install.sh
    dest: "{{ role_path }}/files/install.sh"
- command:
    cmd: "sh {{ role_path }}/files/install.sh"
  args:
    creates: "/home/{{ ansible_user }}/.SpaceVim"
# Setting vim as editor. 
- lineinfile:
    path: $HOME/.bashrc
    state: present
    line: export EDITOR=$(which vim)
- command:
    cmd: "screen -d -m vim"
  register: screen_out
  args:
    creates: "/home/{{ ansible_user }}/.cache/vimfiles/repos/"
- template:
    src: init.toml.j2
    dest: "/home/{{ ansible_user }}/.SpaceVim.d/init.toml"
- debug:
    msg: "{{ screen_out }}"
