---
# Prerequisites packages should be installed.
- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ohmyzsh_deps }}""
  become: true
# Download the ohmyzsh installer and execute it.
- get_url:
    url: "https://raw.githubusercontent.com\
         /ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "{{ role_path }}/files/install.sh"
- command:
    cmd: sh  "{{ role_path }}/files/install.sh"
  args:
    creates: "/home/{{ ansible_user }}/.oh-my-zsh"
# Sets zsh shell for ansible user.
- user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  become: true
- shell: chsh -s $(which zsh) "{{ ansible_user }}"
  become: true
- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ zsh_customs.packages }}"
  become: true
- lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    state: present
    line: "{{ zsh_customs.enable_lines }}"
  with_items:
    - "{{ zsh_customs.enable_lines }}"
# Remember to change your terminal settings to use a powerline font to see
# power line symbols correctly.