- name: "Amazon Linux"
  include_tasks: amazon_linux.yml
  when: ansible_facts['distribution'] == 'Amazon'

- name: "Configure zsh in ubuntu boxes"
  include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"
